services:
  python-app:
    container_name: ddev-${DDEV_SITENAME}-python-app
    build: python
    command: [python, /app/app/app.py]
    stdin_open: true
    tty: true
    environment:
      VIRTUAL_HOST: $DDEV_HOSTNAME
#      HTTP_EXPOSE: 8080:8080
#      HTTPS_EXPOSE: 8080:8080
    networks: [default, ddev_default]
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
    - ".:/mnt/ddev_config"
    - "ddev-global-cache:/mnt/ddev-global-cache"
    - "./python:/app"
