services:
  python-database:
    image: postgres:13
    container_name: ddev-${DDEV_SITENAME}-python-database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      HTTP_EXPOSE: 5432:5432
      HTTPS_EXPOSE: 5432:5432
      VIRTUAL_HOST: $DDEV_HOSTNAME
    networks: [default, ddev_default]
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - postgres_data:/var/lib/postgresql/data

  python-fastapi:
    build: python/fastapi
    container_name: ddev-${DDEV_SITENAME}-python-fastapi
    command: uvicorn src.main:app --reload --env-file .development.env --host 0.0.0.0 --port 8000
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - ./python/fastapi:/app
    environment:
      - DATABASE_URL=postgresql://user:password@python-database:5432/test
      - HTTP_EXPOSE=8001:8000
      - HTTPS_EXPOSE=8000:8000
      - VIRTUAL_HOST=$DDEV_HOSTNAME
    networks: [default, ddev_default]
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}

volumes:
  postgres_data:
